package com.example.demo.entity;

import java.util.List;



import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

//create table department(id bigint primary Key generated by default  as IDENTITY,name varchar(100) not null);
@Entity
@Table(name="department")
public class Department {
	@Id
	@GeneratedValue(strategy =GenerationType.IDENTITY)
	@Column(name="id")
	private long id;
	@Column(name="name")
	private String name;
	@OneToMany(mappedBy ="department",cascade = {CascadeType.DETACH,CascadeType.MERGE,CascadeType.PERSIST,
			CascadeType.REFRESH})
	private List<Employee> employee;
	public Department() {
		
	}
	
	public Department(long id, String name, List<Employee> employee) {
		
		this.id = id;
		this.name = name;
		this.employee = employee;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Employee> getEmployee() {
		return employee;
	}

	public void setEmployee(List<Employee> employee) {
		this.employee=employee;
		
	}

	public void addEmployee(Employee employee2) {
	this.employee.add(employee2);
		
	}

	
	
	
	

}
