package com.example.demo.entity;

import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
/**
 create table skill(
 id bigint primary key generated by default as IDENTITY,
 skill varchar(50) not null);
 */
/**
 create table employee_skill(
 employee_id bigint not null,
 skill_id bigint not null ,
 constraint fK_employee_skill_employee_id foreign key(employee_id) references employee(id),
 constraint fk_employee_skill_skill_id foreign key(skill_id)references skill(id));
 */
@Entity
@Table(name="skill")
public class Skill {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="id")
	private long id;
	@Column(name="skill", nullable=false,unique=true)
	private String skill;
	@ManyToMany(cascade = {CascadeType.DETACH,CascadeType.MERGE,CascadeType.PERSIST,
			CascadeType.REFRESH})
	@JoinTable(name="employee_skill",
	joinColumns = @JoinColumn(name="skill_id"),
	inverseJoinColumns = @JoinColumn(name="employee_id"))
	private List<Employee> employee;
	
	public Skill() {}

	public Skill(long id, String skill, List<Employee> employee) {
		this.id = id;
		this.skill = skill;
		this.employee = employee;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getSkill() {
		return skill;
	}

	public void setSkill(String skill) {
		this.skill = skill;
	}

	public List<Employee> getEmployee() {
		return employee;
	}

	public void setEmployee(List<Employee> employee) {
		this.employee = employee;
	}
	
	
	
	

}
